// Re-export Prisma enums and types for easier imports
export * from '@prisma/client';

// Define enums that match the Prisma schema
export enum FailureRecordType {
  TECHNICAL_PROJECT = 'TECHNICAL_PROJECT',
  RESEARCH_PAPER = 'RESEARCH_PAPER',
  RESEARCH_IDEA = 'RESEARCH_IDEA',
  BUSINESS_IDEA = 'BUSINESS_IDEA',
  FUTURE_TECH_IDEA = 'FUTURE_TECH_IDEA',
  AI_PROJECT = 'AI_PROJECT',
}

export enum IdentityMode {
  ANONYMOUS = 'ANONYMOUS',
  PSEUDONYMOUS = 'PSEUDONYMOUS',
  DELAYED_30 = 'DELAYED_30',
  DELAYED_90 = 'DELAYED_90',
  DELAYED_180 = 'DELAYED_180',
  ATTRIBUTED = 'ATTRIBUTED',
}

export enum SubmissionStatus {
  DRAFT = 'DRAFT',
  PENDING_MODERATION = 'PENDING_MODERATION',
  PUBLISHED = 'PUBLISHED',
  ARCHIVED = 'ARCHIVED',
  WITHDRAWN = 'WITHDRAWN',
  FLAGGED = 'FLAGGED',
}

export enum FailurePoint {
  ASSUMPTION_INVALIDATED = 'ASSUMPTION_INVALIDATED',
  DATA_BIAS = 'DATA_BIAS',
  TECHNICAL_CEILING = 'TECHNICAL_CEILING',
  USER_BEHAVIOR_MISMATCH = 'USER_BEHAVIOR_MISMATCH',
  MARKET_ILLUSION = 'MARKET_ILLUSION',
  TIMING_MISMATCH = 'TIMING_MISMATCH',
  SCALING_FAILURE = 'SCALING_FAILURE',
  DISTRIBUTION_FAILURE = 'DISTRIBUTION_FAILURE',
  COST_STRUCTURE = 'COST_STRUCTURE',
}

export enum EvidenceLevel {
  NONE = 'NONE',
  ANECDOTAL = 'ANECDOTAL',
  METRICS = 'METRICS',
  RESEARCH_GRADE = 'RESEARCH_GRADE',
  REPRODUCIBLE = 'REPRODUCIBLE',
}

export enum ReuseType {
  REUSED = 'REUSED',
  AVOIDED = 'AVOIDED',
  REFERENCED = 'REFERENCED',
}

export enum ModerationStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  FLAGGED = 'FLAGGED',
  REJECTED = 'REJECTED',
}

export enum ModerationFlag {
  ILLEGAL_CONTENT = 'ILLEGAL_CONTENT',
  MALWARE_LINK = 'MALWARE_LINK',
  SCAM_PATTERN = 'SCAM_PATTERN',
  HATE_HARASSMENT = 'HATE_HARASSMENT',
  PLAGIARISM_RISK = 'PLAGIARISM_RISK',
  FAKE_CITATION = 'FAKE_CITATION',
  SPAM = 'SPAM',
}
